server:
  port: 8081
  servlet:
    context-path: /api

mybatis:
  # mapper 位置
  mapper-locations: classpath:/mapper/*.xml
  scripting-language-driver:
    freemarker:
      template-file:
        base-dir: mappers/
        path-provider:
          includes-package-path: false
          separate-directory-per-mapper: false
  # mybatis 配置文件
  config-location: classpath:/mybatis-config.xml

spring:
  # 设置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.141.85.27:3306/cbs
    username: admin
    password: Nicksui1992.

# 604800000=7天
jwt:
  secret: d4d886110151cfd7c54ea63f73ceb442e5a0d10de9d69a441681686b533d45af
  expiration:
    milliseconds: 604800000

logging:
  level:
    org:
      springframework:
        boot:
          logging:
            LogLevel: DEBUG