server:
  port: 8081
  servlet:
    context-path: /api

mybatis:
  # mapper 位置
  mapper-locations: classpath:/mapper/*.xml
  scripting-language-driver:
    freemarker:
      template-file:
        base-dir: mappers/
        path-provider:
          includes-package-path: false
          separate-directory-per-mapper: false
  # mybatis 配置文件
  config-location: classpath:/mybatis-config.xml

spring:
  cloud:
    # Vault used for storage sensitive data
    vault:
      uri: http://8.141.85.27:8200
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: secret
        default-context: cbs/db
        additional-contexts:
          - cbs/redis
          - cbs/text
  config:
    import:
      - vault://secret/cbs/db
      - vault://secret/cbs/redis
      - vault://secret/cbs/text
  #import: optional:vault://
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.141.85.27:3306/cbs
    username: ${mysql-cbs.username}
    password: ${mysql-cbs.password}
#  data:
#    redis:
#      host: 8.141.85.27
#      port: 6379
#      password: ${redis.password}
redis:
  host: 8.141.85.27
  port: 6379
  pwd: ${redis.password}

# 604800000=7天
jwt:
  secret: d4d886110151cfd7c54ea63f73ceb442e5a0d10de9d69a441681686b533d45af
  expiration:
    milliseconds: 604800000

logging:
  level:
    org:
      springframework:
        boot:
          logging:
            LogLevel: DEBUG
#        cloud:
#          vault: DEBUG
        data:
          redis: DEBUG