server:
  port: 8081

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  scripting-language-driver:
    freemarker:
      template-file:
        base-dir: mappers/
        path-provider:
          includes-package-path: false
          separate-directory-per-mapper: false
  config-location: classpath:/mybatis-config.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.141.85.27:3306/cbs
    username: admin
    password: Nicksui1992.